### ISSUE TITLE
Should use Mono/.Net 3.5

### ISSUE THREAD

**Issue by rbray89** [EnzoMeertens/KerbalKrashSystem#6] opened 2016-01-12 17:39 UTC
KSP/Unity is currently on .Net 3.5 This is the reason Linq references are causing issues.

**Comment by EnzoMeertens** [comment] 2016-01-12 18:53
Thanks! That does explain a lot.

On a different note: do you perhaps know how to reference (for example) KIS.dll so I get access to the KIS types without KSP loading two instances of KIS?

If I just reference KIS.dll and set "copy to local" to true, my solution will copy KIS.dll to my output solution. This allows my mod to function, but it loads KIS twice. (Two inventories and such).

If I reference KIS.dll and set "copy to local" to false, my solution will not load (missing references) and therefore will not work.

Will generating a TLB help?

Op 12 jan. 2016 18:39 schreef Ryan Bray <notifications@github.com>:

KSP/Unity is currently on .Net 3.5 This is the reason Linq references are causing issues.

**Comment by rbray89** [comment] 2016-01-12 19:23
Right click on your project that depends on another project. Go to Add->Reference..., Under the project tab, check the project that it depends on. This will force VS to generate a dependency and satisfy build requirements.

**Comment by EnzoMeertens** [comment] 2016-01-13 00:37
Hello,
The problem I am having is that I have to reference Kerbal Inventory System (for Types) and that will copy KIS.dll to my output directory (GameData/KerbalKrashSystem/Plugins/), which will cause KSP to import KIS.dll twice, once from GameData/KIS/Plugins/ and once from GameData/KerbalKrashSystem/Plugins/. 
Do you perhaps know if there a way around this or do you know anyone who might know?

Thanks for all your help,
Enzo Meertens

Date: Tue, 12 Jan 2016 11:23:42 -0800

**Comment by rbray89** [comment] 2016-01-13 00:53
I use the Build commands to sidestep this. I use xcopy/copy to copy the
target Dll, and leave the output directory where they are in my projects.
Take a look at Dynamic Texture Loader as an example. What IDE are you
using? I'm on VisualStudio 2015.

**Comment by EnzoMeertens** [comment] 2016-01-13 01:00
I'll try that right now.It's pretty late here, have to get some sleep soon, haha!
I'm on Visual Studio 2013. I didn't like 2015, had some problems the last few times I tried it. 

Date: Tue, 12 Jan 2016 16:53:25 -0800

**Comment by EnzoMeertens** [comment] 2016-01-13 01:03
Nope, still get the following error in the KSP.log:

[ERR 01:59:34.821] AssemblyLoader: Exception loading 'KerbalKrashSystem_KIS_Repair': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0   at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 
Additional information about this exception:
 System.TypeLoadException: Could not load type 'KerbalKrashSystem_KIS_Repair.KerbalKrashSystem_KIS_Helper' from assembly 'KerbalKrashSystem_KIS_Repair, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.	UnityEngine.Debug:LogError(Object)	AssemblyLoader:LoadAssemblies()	:MoveNext()	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)	:MoveNext()	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)	GameDatabase:StartLoad()	:MoveNext()	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)	LoadingScreen:Start()
This is unnecessarily complicated. I just want to use classes from Kerbal Inventory System in my mod.

Date: Tue, 12 Jan 2016 16:53:25 -0800

**Comment by EnzoMeertens** [comment] 2016-01-13 01:08
Sorry for spamming you.Seems there's a clue in my question. The problem isn't the reference to KIS, but some kind of problem in my KerbalKrashSystem_KIS_Helper class.I'll look into it tomorrow.
Thank you so much for your help! 
Good night!

Date: Tue, 12 Jan 2016 16:53:25 -0800

**Comment by EnzoMeertens** [comment] 2016-01-13 14:32
Fixed in the newest version.
Will be uploaded tomorrow.

**Closed by EnzoMeertens** 2016-01-13 14:32 UTC
